### ISSUE TITLE
New NAPALM Driver - napalm-comware-ssh

### ISSUE THREAD

**Issue by xdai555** [napalm-automation-community/napalm-hp-cw7#2]
@mirceaulinic @vincentbernat 

Hi, I'm writing a napalm driver for H3C/HPE Comware V7 network devices, and the project is almost finished, the homepage is: https://github.com/xdai555/napalm-comware-ssh 

> H3C Comware software (it can be simply understood as HPE Comware outside of China, they have almost the same Comware software), website: https://www.h3c.com/en/Products_Technology/Operating_System/ComwareV7/

- About the driver name
    This driver passed testing on H3C Comware V7 only. I don't have HPE devices to test, but I think it also works with HPE (because they're all called Comware).
    So, the new driver was named `napalm-comware-ssh`, it should to be vender(H3C and HPE) independent. If you think it's inappropriate, I will change its name to `napalm-h3c-cw7-ssh`.
    I'll probably write a Comware NETCONF driver in the future, so the name contains ssh.

    
Now I want to submit it to napalm-automation-community (https://github.com/napalm-automation-community), please tell me what I should do, thank you in advance!

**Comment by vincentbernat** [comment]
I don't have anything working. Maybe you can take over the name?

Also note that HPE does not have the same features as H3C: notably, there is no candidate configuration.

**Comment by mirceaulinic** [comment]
I'm not familiar with any of the named platforms, but based on what Vincent mentioned above, I'd stick to `napalm-h3c-cw7-ssh` for now.
I've created https://github.com/napalm-automation-community/napalm-h3c-cw7-ssh and gave @xdai555 admin access, let me know if you have any questions, or if I can be of any help! 😉

**Comment by xdai555** [comment]
> I don't have anything working. Maybe you can take over the name?
> 
> Also note that HPE does not have the same features as H3C: notably, there is no candidate configuration.

Thanks for your reply, and I will use the new name - `napalm-h3c-cw7-ssh` .

**Comment by xdai555** [comment]
> I'm not familiar with any of the named platforms, but based on what Vincent mentioned above, I'd stick to `napalm-h3c-cw7-ssh` for now. I've created https://github.com/napalm-automation-community/napalm-h3c-cw7-ssh and gave @xdai555 admin access, let me know if you have any questions, or if I can be of any help! 😉

Thanks a lot!  
I will change the driver name and push it to [napalm-h3c-cw7-ssh](https://github.com/napalm-automation-community/napalm-h3c-cw7-ssh).   
Another question is: the email address of this organization (napalm-automation@googlegroups.com) seemed to be unavailable, the email I had sent earlier had failed to be delivered.

**Comment by xdai555** [comment]
> I'm not familiar with any of the named platforms, but based on what Vincent mentioned above, I'd stick to `napalm-h3c-cw7-ssh` for now. I've created https://github.com/napalm-automation-community/napalm-h3c-cw7-ssh and gave @xdai555 admin access, let me know if you have any questions, or if I can be of any help! 😉

Thanks a lot!  
I will change the driver name and push it to [napalm-h3c-cw7-ssh](https://github.com/napalm-automation-community/napalm-h3c-cw7-ssh).   
Another question is: the email address of this organization (`napalm-automation@googlegroups.com`) seemed to be unavailable, the email I had sent earlier had failed to be delivered.
